.TH MD2ROFF 1
.SH NAME
md2roff \- convert Markdown text to roff with MS macros
.SH SYNOPSIS
.B md2roff
[-bn] [-t title] [-a author] [file]
.SH DESCRIPTION
md2roff converts the Markdown input in the given file to roff using the MS
macros. If no file is given, md2roff will read from standard input. The
resulting roff source is always outputted to standard output.
.SH USAGE
.TP
.B -b
Put the document title and author in a page by itself.
.TP
.B -n
Don't display the current date when \fB-b\fR is configured.
.TP
.B -t title
Set the document title.
.TP
.B -a author
Set the document author.
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019-2020 Ben O'Neill <ben@benoneill.xyz>. License: GNU
GPLv3+: GNU GPL version 3 or later.
<https://gnu.org/licenses/gpl.html>. This is free software: you are
free to change and redistribute it. There is NO WARRANTY, to the
extent permitted by law.
.SH SEE ALSO
.BR groff (1),
.BR roff (7),
.BR troff (1)
