.TH MD2ROFF 1
.SH NAME
md2roff \- convert Markdown text to roff with MS macros
.SH SYNOPSIS
.B md2roff
.RB [file...]
.SH DESCRIPTION
md2roff converts the Markdown input in the given files to roff using the MS
macros. If no file is given, md2roff will read from standard input. The
resulting roff source is always outputted to standard output.
.SH SEE ALSO
.BR roff (7),
.BR troff (1)
